*filter
:INPUT DROP [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -s 10.10.1.0/24 -i enp0s8 -p icmp -j ACCEPT
-A INPUT -s 10.10.2.0/24 -i enp0s9 -p icmp  -j ACCEPT
-A INPUT -s 10.10.3.0/24 -i enp0s10 -p icmp  -j ACCEPT
-A INPUT -s 10.10.4.0/24 -i enp0s16 -p icmp  -j ACCEPT
-A INPUT -j REJECT --reject-with icmp-host-prohibited
-A FORWARD -d 10.10.1.0/24 -i enp0s8 -j DROP
-A FORWARD -d 10.10.2.0/24 -i enp0s9 -j DROP
-A FORWARD -d 10.10.3.0/24 -i enp0s10 -j DROP
-A FORWARD -d 10.10.4.0/24 -i enp0s16 -j DROP
-A FORWARD -s 10.10.1.0/24 -d 10.10.3.0/24 -i enp0s8 -j ACCEPT
-A FORWARD -s 10.10.2.0/24 -d 10.10.4.0/24 -i enp0s9 -j ACCEPT
-A FORWARD -s 10.10.3.0/24 -d 10.10.1.0/24 -i enp0s10 -j ACCEPT
-A FORWARD -s 10.10.4.0/24 -d 10.10.2.0/24 -i enp0s16 -j ACCEPT
-A FORWARD -j REJECT --reject-with icmp-host-prohibited
COMMIT

*nat
:PREROUTING ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
-A POSTROUTING -o enp0s8 -j MASQUERADE
-A POSTROUTING -o enp0s9 -j MASQUERADE
-A POSTROUTING -o enp0s10 -j MASQUERADE
-A POSTROUTING -o enp0s16 -j MASQUERADE
COMMIT
